// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEaNs_TZjKlZKwHotdPF08Ncb1yWv75gA',
    appId: '1:662884241834:web:27da3140fa12853c755bd3',
    messagingSenderId: '662884241834',
    projectId: 'diagnost-a439a',
    authDomain: 'diagnost-a439a.firebaseapp.com',
    storageBucket: 'diagnost-a439a.firebasestorage.app',
    measurementId: 'G-1ZG4JP26ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARxOM8ayNt3oLWkhSJAMsL1r8EEsRJVT0',
    appId: '1:662884241834:android:72721fa8c15319a1755bd3',
    messagingSenderId: '662884241834',
    projectId: 'diagnost-a439a',
    storageBucket: 'diagnost-a439a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXhIMXCua__nxooxLppOxBTcHfq10kkCo',
    appId: '1:662884241834:ios:1748fd887e1a4135755bd3',
    messagingSenderId: '662884241834',
    projectId: 'diagnost-a439a',
    storageBucket: 'diagnost-a439a.firebasestorage.app',
    iosBundleId: 'com.example.diagnost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXhIMXCua__nxooxLppOxBTcHfq10kkCo',
    appId: '1:662884241834:ios:1748fd887e1a4135755bd3',
    messagingSenderId: '662884241834',
    projectId: 'diagnost-a439a',
    storageBucket: 'diagnost-a439a.firebasestorage.app',
    iosBundleId: 'com.example.diagnost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEaNs_TZjKlZKwHotdPF08Ncb1yWv75gA',
    appId: '1:662884241834:web:cf620d7dd09a1455755bd3',
    messagingSenderId: '662884241834',
    projectId: 'diagnost-a439a',
    authDomain: 'diagnost-a439a.firebaseapp.com',
    storageBucket: 'diagnost-a439a.firebasestorage.app',
    measurementId: 'G-F7BN8MD4Z3',
  );
}
